### ISSUE TITLE
deploy후 containerList 화면 구성 문제

### ISSUE THREAD

**Issue by ahjheeju129** [jungeuno/NonStop4#15]
로그인하고 보여지는 containerList화면은 잘 동작하는데,
deploy하고 보여지는 containerList에서는 오류 발생

**Comment by jungeuno** [comment]
user_email 를 oauth2,email 로 main.py에서 수정하여 해결

**Comment by jungeuno** [comment]
해결된 줄 알았으나, 실행결과가 동일함.
/services 경로를 /containerList.html 로 변경하면 해결될 것으로 예상

**Comment by ahjheeju129** [comment]
접근에 따라서 localStorage값이 이미 설정되어 있는지 확인하고 없는 경우에만 새롭게 저장하는 방법으로 해결함

**Comment by ahjheeju129** [comment]
접근에 따라서 localStorage값이 이미 설정되어 있는지 확인하고 없는 경우에만 새롭게 저장하는 방법으로 해결함

**Comment by ahjheeju129** [comment]
접근에 따라서 localStorage값이 이미 설정되어 있는지 확인하고 없는 경우에만 새롭게 저장하는 방법으로 해결함
